OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_ZbNZ8XFfAVEPqgXVPCxk7G5s"
MAPBOX_TOKEN="pk.eyJ1IjoiaGFubmFoeXpoYW8iLCJhIjoiY2xwYzNvbHQyMGs4eTJrcW93MGdzajNhNCJ9.yrC6qNXzb0MdYB_y7UqTow"
