OPENAI_API_KEY="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"
OPENAI_ASSISTANT_ID="asst_ZbNZ8XFfAVEPqgXVPCxk7G5s"
MAPBOX_TOKEN="pk.eyJ1IjoiaGFubmFoeXpoYW8iLCJhIjoiY2xwYzNvbHQyMGs4eTJrcW93MGdzajNhNCJ9.yrC6qNXzb0MdYB_y7UqTow"
